### ISSUE TITLE
Auto-detect most likely download

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/website#10]
In the old setup, we did server-side detection (Based on the User-Agent) what the most likely download is that you would be needing. In the new setup we cannot do this server-side anymore, so we need a client-side detection script for this.

https://www.staging.openttd.org/downloads/openttd-releases/1.8.0.html

Here we would like to see only 'win64' if you use Windows on a 64bit system. This greatly reduces the amount of bug-tickets because people downloaded the wrong binary.

**Comment by glx22** [comment]
I guess something using navigator.userAgent should work ( https://www.w3schools.com/js/tryit.asp?filename=tryjs_nav_userAgent )

**Comment by TrueBrain** [comment]
Possibly another idea is to use something like this:

https://github.com/bestiejs/platform.js/blob/master/platform.js

Then we don't have to figure out all the quirks of Browsers :D

**Comment by TrueBrain** [comment]
Best library I could find:
https://github.com/faisalman/ua-parser-js

Does OS and Arch detection, and pretty well. Seems good maintained.
