### ISSUE TITLE
Make the copyright in the bottom automatically bump years

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/website#11]
https://www.staging.openttd.org/index.html, on the bottom of this page is a copyright notice with <from-year>-<to-year>. It would be good if the latter was automatically "current year" (build-time).

We will forget to bump the year otherwise, year in / year out :D

**Comment by LordAro** [comment]
Presuming you mean "at build time", rather than some wonky js to make it automatically update? The latter seems... wrong

**Comment by TrueBrain** [comment]
Yes yes! Build time! No javascript for this :D
