### ISSUE TITLE
Wrong link target of the link on the OpenTTD-lettering in the page header

### ISSUE THREAD

**Issue by auge8472** [OpenTTD/website#139]
The link leads always to the current page. Is this intended? I would expect the homepage (index.html) to be the target of this link.

![openttd-logo-wrong-target](https://user-images.githubusercontent.com/1734660/72014694-b1d50b80-3260-11ea-8a42-108816dfd565.png)

**Comment by LordAro** [comment]
I agree, seems like a bug
