### ISSUE TITLE
Download specific version page

### ISSUE THREAD

**Issue by MingweiSamuel** [OpenTTD/website#149]
The old download url was: http://www.openttd.org/en/download-stable/1.9.3  
This now redirects to: https://www.openttd.org/downloads/openttd-releases/1.9.3.html which 404s

So it seems that the version download is broken or I don't know the right url

**Comment by auge8472** [comment]
I can confirm the problem. The server redirects the request as described and returns status 404.

@MingweiSamuel As a workaround you can use the link to [latest stable](https://www.openttd.org/downloads/openttd-releases/latest.html) which is currently version 1.9.3. You'll find the link also in the download links block in the header of the OpenTTD-website.

**Comment by planetmaker** [comment]
It now should be something like https://cdn.openttd.org/openttd-releases/

**Comment by MingweiSamuel** [comment]
Previously there was a separate HTML page for each version, but just linking to https://cdn.openttd.org/openttd-releases/1.9.2/ (for example) is probably good enough for our purposes

**Comment by TrueBrain** [comment]
Oops, I knew I forgot something... redirects! Will fix that soon :)

We removed the fancy HTML for all but latest, as it simplified the infrastructure a lot. So the URL you found replaces it. I will make the old URLs redirect to this new location. Not as fancy, but contains all the required bits and pieces.

If you have a good use case why older versions should have a fancy page, feel free to let us know. Always a change we readd it :)

**Comment by TrueBrain** [comment]
Ps: please always use https://www.openttd.org/downloads/openttd-releases/latest.html if possible, as that points to the latest stable. The above is only useful in multiplayer scenarios where you want to pin down a version for your players.

**Comment by TrueBrain** [comment]
Took a bit longer than expected to fix, but this should now be fixed :) Let me know if you find any other issues :)

Tnx for the report!
