### ISSUE TITLE
Changelog links on download pages lead to 404 due to text to markdown renames

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/website#330]
changelog.txt was renamed to changelog.md in https://github.com/OpenTTD/OpenTTD/pull/12994

Since then the changelog link in [_layouts/download.html](https://github.com/OpenTTD/website/blob/main/_layouts/download.html) 404s for nightly builds.

**Comment by auge8472** [comment]
I searched for changelog.txt in the repository and found several release postings with a link to the changelog.txt. Those links arde still working. Are there any plans to repack the older relases with a changelog.md?

**Comment by LordAro** [comment]
I doubt we'll be wanting to touch the older releases

**Comment by auge8472** [comment]
Thank you for clarification. A PR will follow in a few minutes.
