### ISSUE TITLE
Can't select 1.8.0 as maximum openttd version

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/website#60]
![2019-02-17](https://user-images.githubusercontent.com/43006711/52918976-4820db80-32f5-11e9-95c6-dce5ca86cd9a.png)
I want to make one of my NewGRFs unavailable for 1.9.0, as the problem it solves is already fixed. I can only select 1.6.0 as maximum version. I need to be able to select 1.8.0.

**Comment by TrueBrain** [comment]
The screenshot shows BaNaNaS. This repository is only about the main webpage. So sadly, in this repository we cannot fix this.

Possibly best thing to do is either make a thread on the [forum](https://www.tt-forums.net/viewforum.php?f=55&sid=4573ebbb2fb1b14169fb66d6b9206d1d), or send an email to [info@](https://www.openttd.org/contact.html). Someone should either be able to fix it, or tell you how to overcome this hurdle. Tnx!
