### ISSUE TITLE
Does the website have a multilingual plan?

### ISSUE THREAD

**Issue by gyf9835** [OpenTTD/website#61]
Does the website have a multilingual plan?

**Comment by claman** [comment]
In terms of language-specific translations?

**Comment by andythenorth** [comment]
There is no firm plan afaik.  Current state:

* the website is generated as static files using Jekyll
* Jekyll has a number of i18n (multi-lingual) plugins available
* in principle, I believe we do want a translated site, but none of the current contributors has time to make this happen themselves
* I can't comment on configuring how the site would be served for different lang locales, with a static site using /en/, /de, /fr, /cn might be simplests but @Truebrain is the best person to comment on that.
* I don't think we'd need to use a webtranslator like [url=eints]https://translator.openttd.org/ immediately, we could do translations on PR until there's enough volume to justify a service 

A quick google search finds https://www.klaasnotfound.com/2017/02/16/proper-multilingual-site-with-github-pages-and-jekyll/ and https://polyglot.untra.io/ but I haven't explored these further.

Assuming that there are no blockers to i18n, then we'd welcome contributions for this :)  To get it done needs:

* contributors to implement the i18n in the Jekyll page templates
* translators for the page templates, and for the content

**Comment by TrueBrain** [comment]
I still like this idea, but as nobody has taken this up in 10 months, going to close the idea for now. If someone feels up for it, I would love to see a PR!
