### ISSUE TITLE
Download links in header too long

### ISSUE THREAD

**Issue by steffhip** [OpenTTD/website#77]
The text of the download links in the header (inside the gray download box) are too long and thus generate an unwanted linebreak.

Solution might be:
* adjust the css settings for the width (#download-fast{1,2,3}) from currently 160px to e.g. 190 px.
* increase the width of the graphic (download-fast.png) for the download field accordingly

**Comment by auge8472** [comment]
It would be better to remove the background graphic and replace it by CSS-rules for background-color and border for the container of the links. I'm willing to make a proposal as PR in the next days.

**Comment by PeterN** [comment]
Too long for what? Can you post screenshots, because I don't see it.

**Comment by steffhip** [comment]
Too long to fit into the downloadbox without linebreak:
<img width="194" alt="detail" src="https://user-images.githubusercontent.com/21207827/55689993-17236580-598c-11e9-9e20-eb618c91a690.png">

**Comment by PeterN** [comment]
Which browser is that? Neither Edge, Chrome or Firefox on PC do this.

**Comment by steffhip** [comment]
Firefox(66) and Chromium(73) running under Linux.

**Comment by spnda** [comment]
On Android with newest Chrome on 720p this doesn't happen either.

**Comment by planetmaker** [comment]
FF 62 under linux doesn't do that thing and shows it as it should in one line

**Comment by Eddi-z** [comment]
probably has more to do with the system font rather than which browser is being used?

can't reproduce this either with firefox or Falkon.

**Comment by TrueBrain** [comment]
It indeed is a font thingy; over the years I added some more and more pixels to the box to fit for everybody, but with the new nightly name it ran out of space again. Adding more pixels is not fully trivial because of the way it is created. Indeed, using CSS stuff for this would be better; someone was working on that, but I have read that for a few months now. So not sure how that is going exactly ;)

Possibly quickest solution is to extend the image again, giving it some more space. 10px or so should be sufficient already, but I guess 200px or so would be fine too.

Anyone up making a PR for that? Tnx :D

**Comment by auge8472** [comment]
> probably has more to do with the system font rather than which browser is being used?

It's not only a thing of the choosed font itself but also a thing of it's *font size*. The site was designed years ago with a typical font in a typical font size (13 or 14 pixels at that time) in mind. So the background image for the block was sized to fit two lines (links to nightly and stable). Back then the block got overcrowded, when it has to contain three lines of links (nightly, beta or release candidate and stable).

For now I can say, that the block is large enough in Firefox with no minimal font size set but to small with a minimal font size of 14px. I can see this behaviour in Windows 10 *and* in Ubuntu 16.04.06. A similar but at the same time different behaviour I can see in Vivaldi (Chromium engine). There is no minimal font size set but when I play with the zoom slider and set the page zoom down to 80%, the link to the nightly breaks out of the container. This happens only in Windows but not in Ubuntu.

So we can assume that it is a combination of the font used in reality (dependient from the system of the user) and of the font size settings in the browser. As a website creator one has no information about the real conditions on a system. That is inherent to the system. So a CSS ruleset that let the block shrink or grow with it's content is the best solution.

**Comment by auge8472** [comment]
I opened a pull request for a resizeable download header (#79).

**Comment by auge8472** [comment]
I think it's time to close the issue because it was solved with #79.

**Comment by steffhip** [comment]
I can confirm the issue is now solved.
(Tested with FF66 and Chromium 74 on the machine which showed this issue in the past and the links are now shown correctly)
